title:    
logo:  "/assets/img/github1.jpg?raw=true" 
description: Business Analyst | Data Scientist 
show_downloads: true
google_analytics:    
theme: jekyll-theme-minimal
#jekyll-theme-tactile
#jekyll-theme-slate
