title:    
logo:  "/assets/img/protfolio.JPG?raw=true" 
description: Business Analytics | Data Scientist 
show_downloads: true
google_analytics:    
theme:     jekyll-theme-tactile
#jekyll-theme-slate
