title:    
logo: "<img src="/assets/img/github1.jpg" width="300" height="200" class="img-responsive" alt=""> "
logo: "/assets/img/github2.jpg" 
logo: "/assets/img/github3.jpg?raw=true" 
description: "<img src="/assets/img/github1.jpg" width="300" height="200" class="img-responsive" alt=""> "
description: Business Analyst | Data Scientist 
description: 11111
description: ssssss
show_downloads: true
google_analytics:    
theme: jekyll-theme-minimal
#jekyll-theme-tactile
#jekyll-theme-slate
